CREATE SCHEMA "sakila";

CREATE COLUMN TABLE "sakila"."actor" (
  "actor_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "first_name" NVARCHAR(45) NOT NULL,
  "last_name" NVARCHAR(45) NOT NULL,
  "last_update" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("actor_id")
);

CREATE COLUMN TABLE "sakila"."film" (
  "film_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "title" NVARCHAR(255) NOT NULL,
  "description" NCLOB,
  "release_year" INTEGER,
  "length" SMALLINT,
  "rental_rate" DECIMAL(4,2),
  PRIMARY KEY ("film_id")
);

CREATE COLUMN TABLE "sakila"."film_actor" (
  "actor_id" INTEGER NOT NULL,
  "film_id" INTEGER NOT NULL,
  PRIMARY KEY ("actor_id", "film_id"),
  FOREIGN KEY ("actor_id") REFERENCES "sakila"."actor" ("actor_id"),
  FOREIGN KEY ("film_id") REFERENCES "sakila"."film" ("film_id")
);

CREATE INDEX "idx_actor_last_name" ON "sakila"."actor" ("last_name");

CREATE VIEW "sakila"."film_list" AS
  SELECT f."film_id", f."title", f."release_year", a."first_name" || ' ' || a."last_name" AS "actor"
  FROM "sakila"."film" f
  JOIN "sakila"."film_actor" fa ON f."film_id" = fa."film_id"
  JOIN "sakila"."actor" a ON fa."actor_id" = a."actor_id";

INSERT INTO "sakila"."actor" ("first_name", "last_name") VALUES ('PENELOPE', 'GUINESS');
INSERT INTO "sakila"."actor" ("first_name", "last_name") VALUES ('NICK', 'WAHLBERG');
INSERT INTO "sakila"."actor" ("first_name", "last_name") VALUES ('ED', 'CHASE');
INSERT INTO "sakila"."actor" ("first_name", "last_name") VALUES ('JENNIFER', 'DAVIS');

INSERT INTO "sakila"."film" ("title", "description", "release_year", "length", "rental_rate") VALUES ('ACADEMY DINOSAUR', 'An epic drama of a feminist and a mad scientist', 2006, 86, 0.99);
INSERT INTO "sakila"."film" ("title", "description", "release_year", "length", "rental_rate") VALUES ('ACE GOLDFINGER', 'An astounding epistle of a database administrator', 2006, 48, 4.99);
INSERT INTO "sakila"."film" ("title", "description", "release_year", "length", "rental_rate") VALUES ('ADAPTATION HOLES', 'A reflective tale of a car and a monkey', 2006, 50, 2.99);

INSERT INTO "sakila"."film_actor" ("actor_id", "film_id") VALUES (1, 1);
INSERT INTO "sakila"."film_actor" ("actor_id", "film_id") VALUES (1, 2);
INSERT INTO "sakila"."film_actor" ("actor_id", "film_id") VALUES (2, 1);
INSERT INTO "sakila"."film_actor" ("actor_id", "film_id") VALUES (3, 3);
INSERT INTO "sakila"."film_actor" ("actor_id", "film_id") VALUES (4, 3);
