// THIS FILE IS AUTOGENERATED BY typesGenerator.js
declare interface IBksConfig {
    db: {
        cockroachdb: {
            connectionTimeout: number;
            idleTimeout: number;
            maxClient: number;
        };
        mariadb: {
            connectTimeout: number;
        };
        mysql: {
            connectTimeout: number;
        };
        postgres: {
            connectionTimeout: number;
            idleTimeout: number;
            maxClient: number;
        };
        redshift: {
            connectionTimeout: number;
            idleTimeout: number;
            maxClient: number;
        };
    };
    general: {
        checkForUpdatesInterval: number;
        dataSyncInterval: number;
        workspaceSyncInterval: number;
    };
    keybindings: {
        general: {
            addRow: string;
            cloneSelection: string;
            copySelection: string;
            deleteSelection: string;
            openInSqlEditor: string;
            openQuickSearch: string;
            pasteSelection: string;
            refresh: string[];
            save: string;
        };
        queryEditor: {
            copyResultSelection: string;
            selectEditor: string;
            selectNextResult: string;
            selectPreviousResult: string;
            submitCurrentQueryToFile: string;
            submitQueryToFile: string;
            switchPaneFocus: string;
        };
        quickSearch: {
            altOpen: string;
            altOpenInBackground: string;
            close: string;
            focusSearch: string[];
            open: string;
            openInBackground: string;
            selectDown: string[];
            selectUp: string[];
        };
        tab: {
            closeTab: string;
            nextTab: string[];
            previousTab: string[];
            reopenLastClosedTab: string;
            switchTab1: string;
            switchTab2: string;
            switchTab3: string;
            switchTab4: string;
            switchTab5: string;
            switchTab6: string;
            switchTab7: string;
            switchTab8: string;
            switchTab9: string;
        };
        tableTable: {
            focusOnFilterInput: string;
            nextPage: string;
            openEditorModal: string;
            previousPage: string;
        };
    };
    ui: {
        export: {
            errorNoticeTimeout: number;
        };
        general: {
            binaryEncoding: string;
        };
        layout: {
            mainContentMinWidth: number;
            primarySidebarMinWidth: number;
            secondarySidebarMinWidth: number;
        };
        queryEditor: {
            maxResults: number;
        };
        tableList: {
            itemHeight: number;
        };
        tableTable: {
            defaultColumnWidth: number;
            largeFieldWidth: number;
            maxColumnWidth: number;
            maxInitialWidth: number;
            minColumnWidth: number;
            pageSize: number;
        };
        tableTriggers: {
            maxColumnWidth: number;
        };
    };
};

