// THIS FILE IS AUTOGENERATED BY typesGenerator.ts
declare interface IBksConfig {
    azure: {
        azSQLLoginScope: string;
        ssoPrompt: string;
    };
    db: {
        bedrock: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: string[];
                numbered: string[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        bigquery: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: string[];
                numbered: any[];
                positional: boolean;
                quoted: string[];
            };
            requestTimeout: number;
        };
        cassandra: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        clickhouse: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        cockroachdb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectionTimeout: number;
            idleTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: string[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        default: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        duckdb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        dynamodb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            columnSampleSize: number;
            cursorFetchTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        firebird: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        greengage: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectionTimeout: number;
            idleTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: string[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        libsql: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        mariadb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        mongodb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        mysql: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        oracle: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        postgres: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectionTimeout: number;
            idleTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: string[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        redis: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        redshift: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectionTimeout: number;
            idleTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: string[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        scylladb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        snowflake: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectionTimeout: number;
            idleTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        sqlanywhere: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        sqlite: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: string[];
                numbered: string[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        sqlserver: {
            acquireTimeout: number;
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: string[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        starrocks: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        surrealdb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            connectionTimeout: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        tidb: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
        trino: {
            allowSkipToLastPage: boolean;
            autoRollbackWarningWindow: number;
            autocompleteQuoteCharacter: number;
            manualTransactionTimeout: number;
            maxConnections: number;
            maxReservedConnections: number;
            paramTypes: {
                named: any[];
                numbered: any[];
                positional: boolean;
                quoted: any[];
            };
            requestTimeout: number;
        };
    };
    general: {
        checkForUpdatesDisabled: boolean;
        checkForUpdatesInterval: number;
        downloadUserAgent: string;
        workspaceSyncInterval: number;
    };
    keybindings: {
        general: {
            addRow: string;
            cloneSelection: string;
            copySelection: string;
            deleteSelection: string[];
            jsonViewerSidebar: string;
            openInSqlEditor: string;
            openQuickSearch: string;
            pasteSelection: string;
            redo: string[];
            refresh: string[];
            save: string;
            undo: string;
        };
        plugins: {
            "bks-ai-shell": {
                "new-tab-dropdown-item": string;
            };
        };
        queryEditor: {
            closeTableFilter: string;
            copyResultSelection: string;
            manualCommit: string;
            manualRollback: string;
            openTableFilter: string;
            primaryQueryAction: string[];
            primaryQueryToFileAction: string;
            secondaryQueryAction: string[];
            secondaryQueryToFileAction: string;
            selectEditor: string;
            selectNextResult: string;
            selectPreviousResult: string;
            switchPaneFocus: string;
        };
        quickSearch: {
            altOpen: string;
            altOpenInBackground: string;
            close: string;
            focusSearch: string[];
            open: string;
            openInBackground: string;
            selectDown: string[];
            selectUp: string[];
        };
        resultTable: {
            openEditorModal: string;
        };
        tab: {
            closeTab: string;
            forceCloseTab: string;
            nextTab: string[];
            previousTab: string[];
            reopenLastClosedTab: string;
            switchTab1: string;
            switchTab2: string;
            switchTab3: string;
            switchTab4: string;
            switchTab5: string;
            switchTab6: string;
            switchTab7: string;
            switchTab8: string;
            switchTab9: string;
        };
        tableTable: {
            firstPage: string;
            focusOnFilterInput: string;
            lastPage: string;
            nextPage: string;
            nullSelection: string;
            openEditorModal: string;
            pasteAsNewRows: string;
            previousPage: string;
        };
    };
    pluginSystem: {
        allow: string[];
        communityDisabled: boolean;
        disabled: boolean;
    };
    plugins: {
        "bks-ai-shell": {
            disabled: boolean;
        };
        "bks-er-diagram": {
            disabled: boolean;
        };
    };
    security: {
        activityEvents: string[];
        activityReportIntervalSeconds: number;
        allowRuntimeExtensions: boolean;
        disableSshConfigMatchExec: boolean;
        disconnectOnIdle: boolean;
        disconnectOnLock: boolean;
        disconnectOnSuspend: boolean;
        idleCheckIntervalSeconds: number;
        idleThresholdSeconds: number;
        lockMode: string;
        minPinLength: number;
    };
    ui: {
        export: {
            errorNoticeTimeout: number;
        };
        general: {
            binaryEncoding: string;
        };
        layout: {
            defaultGlobalSidebarItem: string;
            mainContentMinWidth: number;
            primarySidebarMinWidth: number;
            secondarySidebarMinWidth: number;
        };
        queryEditor: {
            autocomplete: {
                keywordCasing: string;
                quoteIdentifiers: string;
            };
            defaultFormatter: string;
            maxResults: number;
            primaryQueryAction: string;
            secondaryQueryAction: string;
        };
        tableList: {
            itemHeight: number;
        };
        tableTable: {
            defaultColumnWidth: number;
            editTrigger: string;
            largeFieldWidth: number;
            maxColumnWidth: number;
            maxInitialWidth: number;
            minColumnWidth: number;
            pageSize: number;
        };
        tableTriggers: {
            maxColumnWidth: number;
        };
    };
}

