/** Run this file to generate the types for the config */

import fs from "fs";
import * as dtsGen from "dts-gen";
import path from "path";
import { parseIni, processRawConfig, recurse } from "./helpers";
import _ from "lodash";
import { isTaggedString } from "./tags";

function resolveRootPath(): string {
  const __dirname = path.resolve();
  const dirpath = path.resolve(__dirname);
  if (dirpath.includes("node_modules")) {
    return dirpath.split("node_modules")[0];
  }
  return dirpath;
}

export function generateConfigTypes(): void {
  const rootPath = resolveRootPath();

  const rawConfig = fs.readFileSync(
    path.join(rootPath, "default.config.ini"),
    "utf-8"
  );

  const config = parseIni(rawConfig);

  const processedConfig = processRawConfig(config);

  // Simplify keybinding types
  for (const { value, parent, key } of recurse(
    processedConfig.keybindings as object
  )) {
    if (isTaggedString(value)) {
      parent[key] =
        value.default ?? value.linux ?? value.mac ?? value.windows ?? value;
    }
  }

  const result =
    "// THIS FILE IS AUTOGENERATED BY typesGenerator.ts\n" +
    dtsGen
      .generateIdentifierDeclarationFile("IBksConfig", processedConfig)
      .replace("declare const IBksConfig:", "declare interface IBksConfig");

  fs.writeFileSync(
    path.join(rootPath, "src/typings/bksConfig.d.ts"),
    result
  );
}

if (process.env.CLI_MODE) {
  generateConfigTypes();
}
