/** Run this file to generate the types for the config */

import fs from "fs";
import * as dtsGen from "dts-gen";
import path from "path";
import { parseIni, processRawConfig } from "./helpers";

function resolveRootPath(): string {
  const __dirname = path.resolve();
  const dirpath = path.resolve(__dirname);
  if (dirpath.includes("node_modules")) {
    return dirpath.split("node_modules")[0];
  }
  return dirpath;
}

export function generateConfigTypes(): void {
  const rootPath = resolveRootPath();

  const rawConfig = fs.readFileSync(
    path.join(rootPath, "default.config.ini"),
    "utf-8"
  );

  const config = parseIni(rawConfig);

  const processedConfig = processRawConfig(config);

  const result =
    "// THIS FILE IS AUTOGENERATED BY typesGenerator.ts\n" +
    dtsGen
      .generateIdentifierDeclarationFile("IBksConfig", processedConfig)
      .replace("declare const IBksConfig:", "declare interface IBksConfig");

  fs.writeFileSync(
    path.join(rootPath, "src/typings/bksConfig.d.ts"),
    result
  );
}

if (process.env.CLI_MODE) {
  generateConfigTypes();
}
