import type { BksVersion } from '@/lib/license';
import type { Platform } from '@/types';

export interface IPlatformInfo {
  isWindows: boolean,
  isMac: boolean,
  isArm: boolean,
  oracleSupported: boolean,
  parsedArgs: any,
  isLinux: boolean,
  sessionType: string,
  isWayland: boolean,
  isSnap: string,
  isPortable: string,
  isDevelopment: boolean,
  isAppImage: boolean,
  sshAuthSock: string,
  environment: string,
  resourcesPath: string,
  env: {
    development: boolean,
    test: boolean,
    production: boolean
  },
  debugEnabled: boolean,
  DEBUG: string,
  platform: Platform,
  darkMode: boolean,
  userDirectory: string,
  downloadsDirectory: string,
  homeDirectory: string,
  pluginsDirectory: string,
  testMode: boolean,
  appDbPath: string,
  updatesDisabled: boolean,
  appVersion: string,
  parsedAppVersion: BksVersion,
  cloudUrl: string,
  locale: string,
}
