// Integration tests for Bedrock (Expensify's SQLite-over-MySQL-wire DB).
//
// Bedrock has no official docker image and no drop-in testcontainers setup.
// A community image exists (r3dsh/bedrockdb on Docker Hub) but is undocumented
// and stale, so we don't wire it into CI blindly. Instead, this spec is
// env-guarded: set BEDROCK_HOST (and optionally BEDROCK_PORT, BEDROCK_USER,
// BEDROCK_PASSWORD) to run the suite against a local Bedrock instance.
//
// Local dev:
//   bedrock -db /tmp/bedrock.db -serverHost 127.0.0.1:8888 ...
//   BEDROCK_HOST=127.0.0.1 yarn test:integration -t bedrock
import knex from "knex";
import { DBTestUtil, dbtimeout } from "../../../../lib/db";
import { runCommonTests } from "./all";

const BEDROCK_HOST = process.env.BEDROCK_HOST;
const BEDROCK_PORT = Number(process.env.BEDROCK_PORT || 8888);
const BEDROCK_USER = process.env.BEDROCK_USER || "";
const BEDROCK_PASSWORD = process.env.BEDROCK_PASSWORD || "";

const describeBedrock = BEDROCK_HOST ? describe : describe.skip;

describeBedrock("Bedrock", () => {
  jest.setTimeout(dbtimeout);

  /** @type {DBTestUtil} */
  let util: DBTestUtil;

  beforeAll(async () => {
    const config = {
      client: "bedrock" as const,
      host: BEDROCK_HOST,
      port: BEDROCK_PORT,
      user: BEDROCK_USER,
      password: BEDROCK_PASSWORD,
      readOnlyMode: false,
    };

    // Bedrock speaks the MySQL wire protocol, so use mysql2 for the test
    // harness's knex connection. SQL generated by knex is MySQL-flavored;
    // Bedrock translates common MySQL DDL to its SQLite backend, but some
    // corners (generated columns, composite keys, etc.) won't round-trip.
    const testKnex = knex({
      client: "mysql2",
      connection: {
        host: BEDROCK_HOST,
        port: BEDROCK_PORT,
        user: BEDROCK_USER,
        password: BEDROCK_PASSWORD,
        database: "test",
      },
      pool: { min: 0, max: 5 },
    });

    util = new DBTestUtil(config as any, "test", {
      dialect: "sqlite",
      knex: testKnex,
      skipGeneratedColumns: true,
    });
    await util.setupdb();
  });

  afterAll(async () => {
    if (util) await util.disconnect();
  });

  describe("Common Tests", () => {
    runCommonTests(() => util);
  });

  it("reports a sqlite version string", async () => {
    const version = await util.connection.versionString();
    expect(version).toBeTruthy();
  });

  it("lists no schemas (sqlite-style)", async () => {
    const schemas = await util.connection.listSchemas();
    expect(schemas).toEqual([]);
  });

  it("lists no routines (sqlite-style)", async () => {
    const routines = await util.connection.listRoutines();
    expect(routines).toEqual([]);
  });
});
