import { Module } from "vuex";
import _ from "lodash";
import { State as RootState } from "@/store";
import { IFolder } from "@/common/interfaces/IQueryFolder";
import {
  ExtendedFolderNode as Node,
  buildFolderNode,
  buildFolderNodes,
} from "@/common/utils/folderTree";
import { ReplacePayload } from "@/store/modules/data/DataModuleBase";

export type State = {
  /** These items should only be generated by the afterMutate action. */
  items: Node[];
  map: Map<Node["id"], Node>;
};

function detachFromParent(map: Map<Node["id"], Node>, node: Node) {
  const parent = map.get(node.parentId);
  if (parent) {
    parent.children.splice(parent.children.indexOf(node), 1);
  }
}

function applyUpsert(state: State, folders: IFolder[]) {
  const attaching: Node[] = [];

  for (const folder of folders) {
    const node = buildFolderNode(folder);
    const existing = state.map.get(node.id);

    if (!existing) {
      const idx = _.sortedIndexBy(state.items, node, "name");
      state.items.splice(idx, 0, node);
      state.map.set(node.id, node);
      attaching.push(node);
      continue;
    }

    existing.name = node.name;
    existing.ref = node.ref;

    // A folder that changed parents keeps its own subtree, it just hangs
    // off somewhere else now.
    if (existing.parentId !== node.parentId) {
      detachFromParent(state.map, existing);
      existing.parentId = node.parentId;
      attaching.push(existing);
    }
  }

  // A second pass, so a node whose parent is later in the batch finds it.
  for (const node of attaching) {
    const parent = state.map.get(node.parentId);
    if (parent) {
      const idx = _.sortedIndexBy(parent.children, node, "name");
      parent.children.splice(idx, 0, node);
    }
  }
}

function applyRemove(state: State, ids: `folder-${number}`[]) {
  // The tree renders through `children`, so dropping the node from
  // `items` alone would leave it on screen under its parent.
  for (const id of ids) {
    if (state.map.has(id)) {
      detachFromParent(state.map, state.map.get(id));
    }
  }

  state.items = state.items.filter((i) => !ids.includes(i.id));
  for (const id of ids) {
    state.map.delete(id);
  }
}

/**
 * Used for tree visualization using <tree> component
 **/
export const FolderNodeModule: Module<State, RootState> = {
  namespaced: true,
  state() {
    return {
      items: [],
      map: new Map(),
    };
  },
  mutations: {
    // ---- Mutations below are triggered by afterMutate action ----
    set(state, folders: IFolder | IFolder[]) {
      folders = Array.isArray(folders) ? folders : [folders];
      folders = folders.toSorted((a, b) => a.name.localeCompare(b.name));
      state.items = buildFolderNodes(folders);
      state.map = new Map(state.items.map((i) => [i.id, i]));
    },
    replace(state, payload: ReplacePayload<IFolder>) {
      const { items, replaceIf } = _.isArray(payload)
        ? { items: payload, replaceIf: null }
        : payload;

      if (!replaceIf) {
        const folders = items.toSorted((a, b) => a.name.localeCompare(b.name));
        state.items = buildFolderNodes(folders);
        state.map = new Map(state.items.map((i) => [i.id, i]));
        return;
      }

      const ids = items.map((i) => `folder-${i.id}`);
      const staleItems = state
        .items
        .filter((i) => !ids.includes(i.id) && replaceIf(i.ref))
        .map((i) => i.id);

      applyRemove(state, staleItems);
      applyUpsert(state, items);
    },
    upsert(state, folders: IFolder | IFolder[]) {
      folders = Array.isArray(folders) ? folders : [folders];
      applyUpsert(state, folders);
    },
    remove(state, folders: IFolder | IFolder[] | number) {
      let ids: `folder-${number}`[];
      if (Array.isArray(folders)) {
        ids = folders.map((f) => `folder-${f.id}` as const);
      } else if (typeof folders === "object") {
        ids = [`folder-${folders.id}`];
      } else {
        ids = [`folder-${folders}`];
      }
      applyRemove(state, ids);
    },
  },
};
