import { Module } from "vuex";
import _ from "lodash";
import { State as RootState } from "@/store";
import { IFolder } from "@/common/interfaces/IQueryFolder";
import {
  ExtendedFolderNode as Node,
  buildFolderNode,
  buildFolderNodes,
  isDraftFolder,
} from "@/common/utils/folderTree";
import { ReplacePayload } from "@/store/modules/data/DataModuleBase";

type State = {
  /** These items should only be generated by the afterMutate action. */
  items: Node[];
};

function asArray<T>(value: T | T[]): T[] {
  return _.isArray(value) ? value : [value];
}

function detachFromParent(items: Node[], node: Node) {
  const parent = items.find((i) => i.id === node.parentId);
  if (parent) {
    parent.children.splice(parent.children.indexOf(node), 1);
  }
}

function applyUpsert(state: State, folders: IFolder[]) {
  const attaching: Node[] = [];

  for (const folder of folders) {
    const node = buildFolderNode(folder);
    const existing = state.items.find((i) => i.id === node.id);

    if (!existing) {
      if (isDraftFolder(folder)) {
        state.items.unshift(node);
      } else {
        state.items.push(node);
      }
      attaching.push(node);
      continue;
    }

    existing.name = node.name;
    existing.ref = node.ref;

    // A folder that changed parents keeps its own subtree, it just hangs
    // off somewhere else now.
    if (existing.parentId !== node.parentId) {
      detachFromParent(state.items, existing);
      existing.parentId = node.parentId;
      attaching.push(existing);
    }
  }

  // A second pass, so a node whose parent is later in the batch finds it.
  for (const node of attaching) {
    const parent = state.items.find((i) => i.id === node.parentId);
    if (parent) {
      if (isDraftFolder(node.ref)) {
        parent.children.unshift(node);
      } else {
        parent.children.push(node);
      }
    }
  }
}

function applyRemove(state: State, ids: string[]) {
  // The tree renders through `children`, so dropping the node from
  // `items` alone would leave it on screen under its parent.
  for (const id of ids) {
    const node = state.items.find((i) => i.id === id);
    if (node) {
      detachFromParent(state.items, node);
    }
  }

  state.items = state.items.filter((i) => !ids.includes(i.id));
}

/**
 * Used for tree visualization using <tree> component
 **/
export const FolderNodeModule: Module<State, RootState> = {
  namespaced: true,
  state() {
    return {
      items: [],
    };
  },
  mutations: {
    // ---- Mutations below are triggered by afterMutate action ----
    set(state, folders: IFolder | IFolder[]) {
      state.items = buildFolderNodes(asArray(folders));
    },
    /** A scoped payload only speaks for its own slice, so nodes outside it survive. */
    replace(state, payload: ReplacePayload<IFolder>) {
      const { items, scope } = _.isArray(payload)
        ? { items: payload, scope: null }
        : payload;

      if (!scope) {
        state.items = buildFolderNodes(items);
        return;
      }

      const ids = items.map((i) => `folder-${i.id}`);
      const stale = state.items.filter(
        (i) => !ids.includes(i.id) && _.isMatch(i.ref, scope)
      );
      applyRemove(state, stale.map((i) => i.id));
      applyUpsert(state, items);
    },
    upsert(state, folders: IFolder | IFolder[]) {
      applyUpsert(state, asArray(folders));
    },
    remove(state, folders: IFolder | IFolder[] | number) {
      const ids = asArray(folders).map(
        (folder) => `folder-${_.isNumber(folder) ? folder : folder.id}`
      );
      applyRemove(state, ids);
    },
  },
};
