/**
 * CSS Variables that are passed to plugins. An entry with `from` is an alias:
 * the plugin sees `name` carrying the computed value of `from`.
 */
export type CssVar = string | { name: string; from: string };

export const cssVars: readonly CssVar[] = [
  "--font-size",
  "--font-family",
  "--font-family-mono",

  "--theme-bg",
  "--theme-base",
  "--theme-primary",
  "--theme-secondary",

  "--text-dark",
  "--text",
  "--text-light",
  "--text-lighter",
  "--text-hint",
  "--text-disabled",

  "--brand-info",
  "--brand-success",
  "--brand-warning",
  "--brand-danger",
  "--brand-default",
  "--brand-purple",
  "--brand-pink",

  "--border-color",
  "--link-color",
  "--placeholder",
  "--selection",
  "--input-highlight",

  "--query-editor-bg",
  "--menu-bg",
  "--menu-shadow",

  "--scrollbar-track",
  "--scrollbar-thumb",

  // BksTextEditor
  "--text-editor-activeline-bg",
  "--text-editor-activeline-gutter-bg",
  "--text-editor-atom-fg",
  "--text-editor-bg",
  "--text-editor-bracket-fg",
  "--text-editor-builtin-fg",
  "--text-editor-comment-attribute-fg",
  "--text-editor-comment-def-fg",
  "--text-editor-comment-fg",
  "--text-editor-comment-tag-fg",
  "--text-editor-comment-type-fg",
  "--text-editor-cursor-bg",
  "--text-editor-fatcursor-bg",
  "--text-editor-def-fg",
  "--text-editor-error-bg",
  "--text-editor-error-fg",
  "--text-editor-fg",
  "--text-editor-focused-outline",
  "--text-editor-font-size",
  "--text-editor-foldgutter-fg",
  "--text-editor-foldgutter-fg-hover",
  "--text-editor-gutter-bg",
  "--text-editor-gutter-border",
  "--text-editor-guttermarker-fg",
  "--text-editor-guttermarker-subtle-fg",
  "--text-editor-header-fg",
  "--text-editor-highlight-bg",
  "--text-editor-indent-marker-bg",
  "--text-editor-indent-marker-active-bg",
  "--text-editor-keyword-fg",
  "--text-editor-linenumber-fg",
  "--text-editor-linenumber-active-fg",
  "--text-editor-link-fg",
  "--text-editor-matchingbracket-fg",
  "--text-editor-matchingbracket-bg",
  "--text-editor-number-fg",
  "--text-editor-property-fg",
  "--text-editor-selected-bg",
  "--text-editor-matchingselection-bg",
  "--text-editor-string-fg",
  "--text-editor-tag-fg",
  "--text-editor-variable-2-fg",
  "--text-editor-variable-3-fg",
  "--text-editor-variable-fg",
  "--text-editor-namespace-fg",
  "--text-editor-type-fg",
  "--text-editor-class-fg",
  "--text-editor-enum-fg",
  "--text-editor-interface-fg",
  "--text-editor-struct-fg",
  "--text-editor-typeParameter-fg",
  "--text-editor-parameter-fg",
  "--text-editor-enumMember-fg",
  "--text-editor-decorator-fg",
  "--text-editor-event-fg",
  "--text-editor-function-fg",
  "--text-editor-method-fg",
  "--text-editor-macro-fg",
  "--text-editor-label-fg",
  "--text-editor-regexp-fg",
  "--text-editor-operator-fg",
  "--text-editor-definition-fg",
  "--text-editor-variableName-fg",
  "--text-editor-bool-fg",
  "--text-editor-null-fg",
  "--text-editor-className-fg",
  "--text-editor-propertyName-fg",
  "--text-editor-punctuation-fg",
  "--text-editor-meta-fg",
  "--text-editor-typeName-fg",
  "--text-editor-labelName-fg",
  "--text-editor-attributeName-fg",
  "--text-editor-attributeValue-fg",
  "--text-editor-heading-fg",
  "--text-editor-url-fg",
  "--text-editor-processingInstruction-fg",
  "--text-editor-special-string-fg",
  "--text-editor-name-fg",
  "--text-editor-deleted-fg",
  "--text-editor-character-fg",
  "--text-editor-color-fg",
  "--text-editor-standard-fg",
  "--text-editor-separator-fg",
  "--text-editor-changed-fg",
  "--text-editor-annotation-fg",
  "--text-editor-modifier-fg",
  "--text-editor-self-fg",
  "--text-editor-operatorKeyword-fg",
  "--text-editor-escape-fg",
  "--text-editor-strong-fg",
  "--text-editor-emphasis-fg",
  "--text-editor-strikethrough-fg",
  "--text-editor-sql-alias-fg",
  "--text-editor-sql-field-fg",

  "--panel-bg",
  "--panel-fg",
  "--panel-bg-hover",
  "--panel-bg-active",

  // Plugins built against the old names keep receiving them.
  { name: "--bks-text-editor-activeline-bg-color", from: "--text-editor-activeline-bg" },
  { name: "--bks-text-editor-activeline-gutter-bg-color", from: "--text-editor-activeline-gutter-bg" },
  { name: "--bks-text-editor-atom-fg-color", from: "--text-editor-atom-fg" },
  { name: "--bks-text-editor-bg-color", from: "--text-editor-bg" },
  { name: "--bks-text-editor-bracket-fg-color", from: "--text-editor-bracket-fg" },
  { name: "--bks-text-editor-builtin-fg-color", from: "--text-editor-builtin-fg" },
  { name: "--bks-text-editor-comment-attribute-fg-color", from: "--text-editor-comment-attribute-fg" },
  { name: "--bks-text-editor-comment-def-fg-color", from: "--text-editor-comment-def-fg" },
  { name: "--bks-text-editor-comment-fg-color", from: "--text-editor-comment-fg" },
  { name: "--bks-text-editor-comment-tag-fg-color", from: "--text-editor-comment-tag-fg" },
  { name: "--bks-text-editor-comment-type-fg-color", from: "--text-editor-comment-type-fg" },
  { name: "--bks-text-editor-cursor-bg-color", from: "--text-editor-cursor-bg" },
  { name: "--bks-text-editor-fatcursor-bg-color", from: "--text-editor-fatcursor-bg" },
  { name: "--bks-text-editor-def-fg-color", from: "--text-editor-def-fg" },
  { name: "--bks-text-editor-error-bg-color", from: "--text-editor-error-bg" },
  { name: "--bks-text-editor-error-fg-color", from: "--text-editor-error-fg" },
  { name: "--bks-text-editor-fg-color", from: "--text-editor-fg" },
  { name: "--bks-text-editor-focused-outline-color", from: "--text-editor-focused-outline" },
  { name: "--bks-text-editor-font-size", from: "--text-editor-font-size" },
  { name: "--bks-text-editor-foldgutter-fg-color", from: "--text-editor-foldgutter-fg" },
  { name: "--bks-text-editor-foldgutter-fg-color-hover", from: "--text-editor-foldgutter-fg-hover" },
  { name: "--bks-text-editor-gutter-bg-color", from: "--text-editor-gutter-bg" },
  { name: "--bks-text-editor-gutter-border-color", from: "--text-editor-gutter-border" },
  { name: "--bks-text-editor-guttermarker-fg-color", from: "--text-editor-guttermarker-fg" },
  { name: "--bks-text-editor-guttermarker-subtle-fg-color", from: "--text-editor-guttermarker-subtle-fg" },
  { name: "--bks-text-editor-header-fg-color", from: "--text-editor-header-fg" },
  { name: "--bks-text-editor-highlight-bg-color", from: "--text-editor-highlight-bg" },
  { name: "--bks-text-editor-indent-marker-bg-color", from: "--text-editor-indent-marker-bg" },
  { name: "--bks-text-editor-indent-marker-active-bg-color", from: "--text-editor-indent-marker-active-bg" },
  { name: "--bks-text-editor-keyword-fg-color", from: "--text-editor-keyword-fg" },
  { name: "--bks-text-editor-linenumber-fg-color", from: "--text-editor-linenumber-fg" },
  { name: "--bks-text-editor-linenumber-active-fg-color", from: "--text-editor-linenumber-active-fg" },
  { name: "--bks-text-editor-link-fg-color", from: "--text-editor-link-fg" },
  { name: "--bks-text-editor-matchingbracket-fg-color", from: "--text-editor-matchingbracket-fg" },
  { name: "--bks-text-editor-matchingbracket-bg-color", from: "--text-editor-matchingbracket-bg" },
  { name: "--bks-text-editor-number-fg-color", from: "--text-editor-number-fg" },
  { name: "--bks-text-editor-property-fg-color", from: "--text-editor-property-fg" },
  { name: "--bks-text-editor-selected-bg-color", from: "--text-editor-selected-bg" },
  { name: "--bks-text-editor-matchingselection-bg-color", from: "--text-editor-matchingselection-bg" },
  { name: "--bks-text-editor-string-fg-color", from: "--text-editor-string-fg" },
  { name: "--bks-text-editor-tag-fg-color", from: "--text-editor-tag-fg" },
  { name: "--bks-text-editor-variable-2-fg-color", from: "--text-editor-variable-2-fg" },
  { name: "--bks-text-editor-variable-3-fg-color", from: "--text-editor-variable-3-fg" },
  { name: "--bks-text-editor-variable-fg-color", from: "--text-editor-variable-fg" },
  { name: "--bks-text-editor-namespace-fg-color", from: "--text-editor-namespace-fg" },
  { name: "--bks-text-editor-type-fg-color", from: "--text-editor-type-fg" },
  { name: "--bks-text-editor-class-fg-color", from: "--text-editor-class-fg" },
  { name: "--bks-text-editor-enum-fg-color", from: "--text-editor-enum-fg" },
  { name: "--bks-text-editor-interface-fg-color", from: "--text-editor-interface-fg" },
  { name: "--bks-text-editor-struct-fg-color", from: "--text-editor-struct-fg" },
  { name: "--bks-text-editor-typeParameter-fg-color", from: "--text-editor-typeParameter-fg" },
  { name: "--bks-text-editor-parameter-fg-color", from: "--text-editor-parameter-fg" },
  { name: "--bks-text-editor-enumMember-fg-color", from: "--text-editor-enumMember-fg" },
  { name: "--bks-text-editor-decorator-fg-color", from: "--text-editor-decorator-fg" },
  { name: "--bks-text-editor-event-fg-color", from: "--text-editor-event-fg" },
  { name: "--bks-text-editor-function-fg-color", from: "--text-editor-function-fg" },
  { name: "--bks-text-editor-method-fg-color", from: "--text-editor-method-fg" },
  { name: "--bks-text-editor-macro-fg-color", from: "--text-editor-macro-fg" },
  { name: "--bks-text-editor-label-fg-color", from: "--text-editor-label-fg" },
  { name: "--bks-text-editor-regexp-fg-color", from: "--text-editor-regexp-fg" },
  { name: "--bks-text-editor-operator-fg-color", from: "--text-editor-operator-fg" },
  { name: "--bks-text-editor-definition-fg-color", from: "--text-editor-definition-fg" },
  { name: "--bks-text-editor-variableName-fg-color", from: "--text-editor-variableName-fg" },
  { name: "--bks-text-editor-bool-fg-color", from: "--text-editor-bool-fg" },
  { name: "--bks-text-editor-null-fg-color", from: "--text-editor-null-fg" },
  { name: "--bks-text-editor-className-fg-color", from: "--text-editor-className-fg" },
  { name: "--bks-text-editor-propertyName-fg-color", from: "--text-editor-propertyName-fg" },
  { name: "--bks-text-editor-punctuation-fg-color", from: "--text-editor-punctuation-fg" },
  { name: "--bks-text-editor-meta-fg-color", from: "--text-editor-meta-fg" },
  { name: "--bks-text-editor-typeName-fg-color", from: "--text-editor-typeName-fg" },
  { name: "--bks-text-editor-labelName-fg-color", from: "--text-editor-labelName-fg" },
  { name: "--bks-text-editor-attributeName-fg-color", from: "--text-editor-attributeName-fg" },
  { name: "--bks-text-editor-attributeValue-fg-color", from: "--text-editor-attributeValue-fg" },
  { name: "--bks-text-editor-heading-fg-color", from: "--text-editor-heading-fg" },
  { name: "--bks-text-editor-url-fg-color", from: "--text-editor-url-fg" },
  { name: "--bks-text-editor-processingInstruction-fg-color", from: "--text-editor-processingInstruction-fg" },
  { name: "--bks-text-editor-special-string-fg-color", from: "--text-editor-special-string-fg" },
  { name: "--bks-text-editor-name-fg-color", from: "--text-editor-name-fg" },
  { name: "--bks-text-editor-deleted-fg-color", from: "--text-editor-deleted-fg" },
  { name: "--bks-text-editor-character-fg-color", from: "--text-editor-character-fg" },
  { name: "--bks-text-editor-color-fg-color", from: "--text-editor-color-fg" },
  { name: "--bks-text-editor-standard-fg-color", from: "--text-editor-standard-fg" },
  { name: "--bks-text-editor-separator-fg-color", from: "--text-editor-separator-fg" },
  { name: "--bks-text-editor-changed-fg-color", from: "--text-editor-changed-fg" },
  { name: "--bks-text-editor-annotation-fg-color", from: "--text-editor-annotation-fg" },
  { name: "--bks-text-editor-modifier-fg-color", from: "--text-editor-modifier-fg" },
  { name: "--bks-text-editor-self-fg-color", from: "--text-editor-self-fg" },
  { name: "--bks-text-editor-operatorKeyword-fg-color", from: "--text-editor-operatorKeyword-fg" },
  { name: "--bks-text-editor-escape-fg-color", from: "--text-editor-escape-fg" },
  { name: "--bks-text-editor-strong-fg-color", from: "--text-editor-strong-fg" },
  { name: "--bks-text-editor-emphasis-fg-color", from: "--text-editor-emphasis-fg" },
  { name: "--bks-text-editor-strikethrough-fg-color", from: "--text-editor-strikethrough-fg" },
  { name: "--bks-text-editor-sql-alias-fg-color", from: "--text-editor-sql-alias-fg" },
  { name: "--bks-text-editor-sql-field-fg-color", from: "--text-editor-sql-field-fg" },
  { name: "--bks-text-editor-context-menu-bg-color", from: "--panel-bg" },
  { name: "--bks-text-editor-context-menu-fg-color", from: "--panel-fg" },
  { name: "--bks-text-editor-context-menu-item-bg-color-active", from: "--panel-bg-active" },
  { name: "--bks-text-editor-context-menu-item-fg-color-active", from: "--panel-fg" },
  { name: "--bks-text-editor-context-menu-item-bg-color-hover", from: "--panel-bg-hover" },
];
