/** CSS Variables that are passed to plugins. A plain string is read as is.
 * A `{ name, value }` entry exposes `name` with `value` resolved against the
 * app, so legacy names can alias the semantic tokens. */
export type CssVar = string | { name: string; value: string };

export const cssVars: readonly CssVar[] = [
  "--font-size",
  "--font-family",
  "--font-family-mono",

  { name: "--theme-bg", value: "var(--bg-base)" },
  { name: "--theme-base", value: "var(--text-contrast)" },
  { name: "--theme-primary", value: "var(--primary-solid-bg)" },
  { name: "--theme-secondary", value: "var(--info-solid-bg)" },

  { name: "--text-dark", value: "var(--text-contrast)" },
  { name: "--text-light", value: "var(--text-muted)" },
  { name: "--text-lighter", value: "var(--text-muted)" },
  { name: "--text-hint", value: "var(--text-muted)" },
  { name: "--text-disabled", value: "var(--text-muted)" },

  { name: "--brand-info", value: "var(--info-solid-bg)" },
  { name: "--brand-success", value: "var(--success-solid-bg)" },
  { name: "--brand-warning", value: "var(--warning-solid-bg)" },
  { name: "--brand-danger", value: "var(--danger-solid-bg)" },
  { name: "--brand-default", value: "var(--solid-bg)" },
  { name: "--brand-purple", value: "var(--purple-9)" },
  { name: "--brand-pink", value: "var(--pink-9)" },

  "--border-color",
  "--text-muted",
  { name: "--link-color", value: "var(--link-fg)" },
  { name: "--placeholder", value: "var(--text-muted)" },
  { name: "--selection", value: "var(--selection-bg)" },
  { name: "--input-highlight", value: "var(--primary-solid-bg)" },

  { name: "--query-editor-bg", value: "var(--bg-base)" },
  { name: "--menu-bg", value: "var(--panel-bg)" },
  { name: "--menu-shadow", value: "var(--panel-shadow)" },

  "--scrollbar-track",
  "--scrollbar-thumb",

  // Semantic color tokens (see assets/styles/themes/utilities.scss)
  "--white",
  "--black",

  "--bg-base",
  "--bg-subtle",
  "--bg",
  "--bg-hover",
  "--bg-active",
  "--border-subtle",
  "--border",
  "--border-hover",
  "--solid-bg",
  "--solid-bg-hover",
  "--text",
  "--text-contrast",
  "--bg-base-a",
  "--bg-subtle-a",
  "--bg-a",
  "--bg-hover-a",
  "--bg-active-a",
  "--border-subtle-a",
  "--border-a",
  "--border-hover-a",
  "--solid-bg-a",
  "--solid-bg-hover-a",
  "--text-a",
  "--text-contrast-a",

  "--primary-bg-base",
  "--primary-bg-subtle",
  "--primary-bg",
  "--primary-bg-hover",
  "--primary-bg-active",
  "--primary-border-subtle",
  "--primary-border",
  "--primary-border-hover",
  "--primary-solid-bg",
  "--primary-solid-bg-hover",
  "--primary-text",
  "--primary-text-contrast",
  "--primary-bg-base-a",
  "--primary-bg-subtle-a",
  "--primary-bg-a",
  "--primary-bg-hover-a",
  "--primary-bg-active-a",
  "--primary-border-subtle-a",
  "--primary-border-a",
  "--primary-border-hover-a",
  "--primary-solid-bg-a",
  "--primary-solid-bg-hover-a",
  "--primary-text-a",
  "--primary-text-contrast-a",
  "--primary-solid-fg",
  "--primary-solid-fg-hover",

  "--info-bg-base",
  "--info-bg-subtle",
  "--info-bg",
  "--info-bg-hover",
  "--info-bg-active",
  "--info-border-subtle",
  "--info-border",
  "--info-border-hover",
  "--info-solid-bg",
  "--info-solid-bg-hover",
  "--info-text",
  "--info-text-contrast",
  "--info-bg-base-a",
  "--info-bg-subtle-a",
  "--info-bg-a",
  "--info-bg-hover-a",
  "--info-bg-active-a",
  "--info-border-subtle-a",
  "--info-border-a",
  "--info-border-hover-a",
  "--info-solid-bg-a",
  "--info-solid-bg-hover-a",
  "--info-text-a",
  "--info-text-contrast-a",
  "--info-solid-fg",
  "--info-solid-fg-hover",

  "--success-bg-base",
  "--success-bg-subtle",
  "--success-bg",
  "--success-bg-hover",
  "--success-bg-active",
  "--success-border-subtle",
  "--success-border",
  "--success-border-hover",
  "--success-solid-bg",
  "--success-solid-bg-hover",
  "--success-text",
  "--success-text-contrast",
  "--success-bg-base-a",
  "--success-bg-subtle-a",
  "--success-bg-a",
  "--success-bg-hover-a",
  "--success-bg-active-a",
  "--success-border-subtle-a",
  "--success-border-a",
  "--success-border-hover-a",
  "--success-solid-bg-a",
  "--success-solid-bg-hover-a",
  "--success-text-a",
  "--success-text-contrast-a",
  "--success-solid-fg",
  "--success-solid-fg-hover",

  "--warning-bg-base",
  "--warning-bg-subtle",
  "--warning-bg",
  "--warning-bg-hover",
  "--warning-bg-active",
  "--warning-border-subtle",
  "--warning-border",
  "--warning-border-hover",
  "--warning-solid-bg",
  "--warning-solid-bg-hover",
  "--warning-text",
  "--warning-text-contrast",
  "--warning-bg-base-a",
  "--warning-bg-subtle-a",
  "--warning-bg-a",
  "--warning-bg-hover-a",
  "--warning-bg-active-a",
  "--warning-border-subtle-a",
  "--warning-border-a",
  "--warning-border-hover-a",
  "--warning-solid-bg-a",
  "--warning-solid-bg-hover-a",
  "--warning-text-a",
  "--warning-text-contrast-a",
  "--warning-solid-fg",
  "--warning-solid-fg-hover",

  "--danger-bg-base",
  "--danger-bg-subtle",
  "--danger-bg",
  "--danger-bg-hover",
  "--danger-bg-active",
  "--danger-border-subtle",
  "--danger-border",
  "--danger-border-hover",
  "--danger-solid-bg",
  "--danger-solid-bg-hover",
  "--danger-text",
  "--danger-text-contrast",
  "--danger-bg-base-a",
  "--danger-bg-subtle-a",
  "--danger-bg-a",
  "--danger-bg-hover-a",
  "--danger-bg-active-a",
  "--danger-border-subtle-a",
  "--danger-border-a",
  "--danger-border-hover-a",
  "--danger-solid-bg-a",
  "--danger-solid-bg-hover-a",
  "--danger-text-a",
  "--danger-text-contrast-a",
  "--danger-solid-fg",
  "--danger-solid-fg-hover",

  "--app-bg",
  "--app-fg",
  "--focus-ring",
  "--btn-icon-fg",
  "--btn-icon-fg-hover",
  "--btn-fg",
  "--btn-fg-hover",
  "--btn-bg",
  "--btn-bg-hover",
  "--btn-bg-active",
  "--btn-shadow",
  "--btn-flat-fg",
  "--btn-flat-fg-hover",
  "--btn-flat-bg",
  "--btn-flat-bg-hover",
  "--btn-flat-shadow",
  "--btn-primary-fg",
  "--btn-primary-fg-hover",
  "--btn-primary-bg",
  "--btn-primary-bg-hover",
  "--btn-primary-shadow",
  "--input-bg",
  "--input-fg",
  "--input-border",
  "--input-border-focus",
  "--select-arrow",
  "--checkbox-bg",
  "--checkbox-border",
  "--checkbox-checked-bg",
  "--checkbox-checked-fg",
  "--link-fg",
  "--selection-bg",
  "--selection-fg",
  "--titlebar-bg",
  "--titlebar-fg",
  "--titlebar-inactive-bg",
  "--titlebar-inactive-fg",
  "--sidebar-bg",
  "--sidebar-fg",
  "--panel-bg",
  "--panel-fg",
  "--panel-bg-hover",
  "--panel-shadow",
  "--overlay-bg",
  "--tree-guide-border",
  "--tree-guide-border-hover",
  "--alert-bg",
  "--alert-fg",
  "--badge-flat-bg",
  "--badge-flat-fg",
  "--badge-solid-bg",
  "--badge-solid-fg",

  // BksTextEditor
  "--editor-activeline-bg",
  "--editor-activeline-gutter-bg",
  "--editor-atom-fg",
  "--editor-bg",
  "--editor-bracket-fg",
  "--editor-builtin-fg",
  "--editor-comment-attribute-fg",
  "--editor-comment-def-fg",
  "--editor-comment-fg",
  "--editor-comment-tag-fg",
  "--editor-comment-type-fg",
  "--editor-cursor-bg",
  "--editor-fatcursor-bg",
  "--editor-def-fg",
  "--editor-error-bg",
  "--editor-error-fg",
  "--editor-fg",
  "--editor-focused-outline",
  "--editor-font-size",
  "--editor-foldgutter-fg",
  "--editor-foldgutter-fg-hover",
  "--editor-gutter-bg",
  "--editor-gutter-border",
  "--editor-guttermarker-fg",
  "--editor-guttermarker-subtle-fg",
  "--editor-header-fg",
  "--editor-highlight-bg",
  "--editor-indent-marker-bg",
  "--editor-indent-marker-active-bg",
  "--editor-keyword-fg",
  "--editor-linenumber-fg",
  "--editor-linenumber-active-fg",
  "--editor-link-fg",
  "--editor-matchingbracket-fg",
  "--editor-matchingbracket-bg",
  "--editor-number-fg",
  "--editor-property-fg",
  "--editor-selected-bg",
  "--editor-matchingselection-bg",
  "--editor-string-fg",
  "--editor-tag-fg",
  "--editor-variable-2-fg",
  "--editor-variable-3-fg",
  "--editor-variable-fg",
  "--editor-namespace-fg",
  "--editor-type-fg",
  "--editor-class-fg",
  "--editor-enum-fg",
  "--editor-interface-fg",
  "--editor-struct-fg",
  "--editor-typeParameter-fg",
  "--editor-parameter-fg",
  "--editor-enumMember-fg",
  "--editor-decorator-fg",
  "--editor-event-fg",
  "--editor-function-fg",
  "--editor-method-fg",
  "--editor-macro-fg",
  "--editor-label-fg",
  "--editor-regexp-fg",
  "--editor-operator-fg",
  "--editor-definition-fg",
  "--editor-variableName-fg",
  "--editor-bool-fg",
  "--editor-null-fg",
  "--editor-className-fg",
  "--editor-propertyName-fg",
  "--editor-punctuation-fg",
  "--editor-meta-fg",
  "--editor-typeName-fg",
  "--editor-labelName-fg",
  "--editor-attributeName-fg",
  "--editor-attributeValue-fg",
  "--editor-heading-fg",
  "--editor-url-fg",
  "--editor-processingInstruction-fg",
  "--editor-special-string-fg",
  "--editor-name-fg",
  "--editor-deleted-fg",
  "--editor-character-fg",
  "--editor-color-fg",
  "--editor-standard-fg",
  "--editor-separator-fg",
  "--editor-changed-fg",
  "--editor-annotation-fg",
  "--editor-modifier-fg",
  "--editor-self-fg",
  "--editor-operatorKeyword-fg",
  "--editor-escape-fg",
  "--editor-strong-fg",
  "--editor-emphasis-fg",
  "--editor-strikethrough-fg",
  "--editor-sql-alias-fg",
  "--editor-sql-field-fg",

  // Plugins built against the old names keep receiving them.
  { name: "--bks-text-editor-activeline-bg-color", value: "var(--editor-activeline-bg)" },
  { name: "--bks-text-editor-activeline-gutter-bg-color", value: "var(--editor-activeline-gutter-bg)" },
  { name: "--bks-text-editor-atom-fg-color", value: "var(--editor-atom-fg)" },
  { name: "--bks-text-editor-bg-color", value: "var(--editor-bg)" },
  { name: "--bks-text-editor-bracket-fg-color", value: "var(--editor-bracket-fg)" },
  { name: "--bks-text-editor-builtin-fg-color", value: "var(--editor-builtin-fg)" },
  { name: "--bks-text-editor-comment-attribute-fg-color", value: "var(--editor-comment-attribute-fg)" },
  { name: "--bks-text-editor-comment-def-fg-color", value: "var(--editor-comment-def-fg)" },
  { name: "--bks-text-editor-comment-fg-color", value: "var(--editor-comment-fg)" },
  { name: "--bks-text-editor-comment-tag-fg-color", value: "var(--editor-comment-tag-fg)" },
  { name: "--bks-text-editor-comment-type-fg-color", value: "var(--editor-comment-type-fg)" },
  { name: "--bks-text-editor-cursor-bg-color", value: "var(--editor-cursor-bg)" },
  { name: "--bks-text-editor-fatcursor-bg-color", value: "var(--editor-fatcursor-bg)" },
  { name: "--bks-text-editor-def-fg-color", value: "var(--editor-def-fg)" },
  { name: "--bks-text-editor-error-bg-color", value: "var(--editor-error-bg)" },
  { name: "--bks-text-editor-error-fg-color", value: "var(--editor-error-fg)" },
  { name: "--bks-text-editor-fg-color", value: "var(--editor-fg)" },
  { name: "--bks-text-editor-focused-outline-color", value: "var(--editor-focused-outline)" },
  { name: "--bks-text-editor-font-size", value: "var(--editor-font-size)" },
  { name: "--bks-text-editor-foldgutter-fg-color", value: "var(--editor-foldgutter-fg)" },
  { name: "--bks-text-editor-foldgutter-fg-color-hover", value: "var(--editor-foldgutter-fg-hover)" },
  { name: "--bks-text-editor-gutter-bg-color", value: "var(--editor-gutter-bg)" },
  { name: "--bks-text-editor-gutter-border-color", value: "var(--editor-gutter-border)" },
  { name: "--bks-text-editor-guttermarker-fg-color", value: "var(--editor-guttermarker-fg)" },
  { name: "--bks-text-editor-guttermarker-subtle-fg-color", value: "var(--editor-guttermarker-subtle-fg)" },
  { name: "--bks-text-editor-header-fg-color", value: "var(--editor-header-fg)" },
  { name: "--bks-text-editor-highlight-bg-color", value: "var(--editor-highlight-bg)" },
  { name: "--bks-text-editor-indent-marker-bg-color", value: "var(--editor-indent-marker-bg)" },
  { name: "--bks-text-editor-indent-marker-active-bg-color", value: "var(--editor-indent-marker-active-bg)" },
  { name: "--bks-text-editor-keyword-fg-color", value: "var(--editor-keyword-fg)" },
  { name: "--bks-text-editor-linenumber-fg-color", value: "var(--editor-linenumber-fg)" },
  { name: "--bks-text-editor-linenumber-active-fg-color", value: "var(--editor-linenumber-active-fg)" },
  { name: "--bks-text-editor-link-fg-color", value: "var(--editor-link-fg)" },
  { name: "--bks-text-editor-matchingbracket-fg-color", value: "var(--editor-matchingbracket-fg)" },
  { name: "--bks-text-editor-matchingbracket-bg-color", value: "var(--editor-matchingbracket-bg)" },
  { name: "--bks-text-editor-number-fg-color", value: "var(--editor-number-fg)" },
  { name: "--bks-text-editor-property-fg-color", value: "var(--editor-property-fg)" },
  { name: "--bks-text-editor-selected-bg-color", value: "var(--editor-selected-bg)" },
  { name: "--bks-text-editor-matchingselection-bg-color", value: "var(--editor-matchingselection-bg)" },
  { name: "--bks-text-editor-string-fg-color", value: "var(--editor-string-fg)" },
  { name: "--bks-text-editor-tag-fg-color", value: "var(--editor-tag-fg)" },
  { name: "--bks-text-editor-variable-2-fg-color", value: "var(--editor-variable-2-fg)" },
  { name: "--bks-text-editor-variable-3-fg-color", value: "var(--editor-variable-3-fg)" },
  { name: "--bks-text-editor-variable-fg-color", value: "var(--editor-variable-fg)" },
  { name: "--bks-text-editor-namespace-fg-color", value: "var(--editor-namespace-fg)" },
  { name: "--bks-text-editor-type-fg-color", value: "var(--editor-type-fg)" },
  { name: "--bks-text-editor-class-fg-color", value: "var(--editor-class-fg)" },
  { name: "--bks-text-editor-enum-fg-color", value: "var(--editor-enum-fg)" },
  { name: "--bks-text-editor-interface-fg-color", value: "var(--editor-interface-fg)" },
  { name: "--bks-text-editor-struct-fg-color", value: "var(--editor-struct-fg)" },
  { name: "--bks-text-editor-typeParameter-fg-color", value: "var(--editor-typeParameter-fg)" },
  { name: "--bks-text-editor-parameter-fg-color", value: "var(--editor-parameter-fg)" },
  { name: "--bks-text-editor-enumMember-fg-color", value: "var(--editor-enumMember-fg)" },
  { name: "--bks-text-editor-decorator-fg-color", value: "var(--editor-decorator-fg)" },
  { name: "--bks-text-editor-event-fg-color", value: "var(--editor-event-fg)" },
  { name: "--bks-text-editor-function-fg-color", value: "var(--editor-function-fg)" },
  { name: "--bks-text-editor-method-fg-color", value: "var(--editor-method-fg)" },
  { name: "--bks-text-editor-macro-fg-color", value: "var(--editor-macro-fg)" },
  { name: "--bks-text-editor-label-fg-color", value: "var(--editor-label-fg)" },
  { name: "--bks-text-editor-regexp-fg-color", value: "var(--editor-regexp-fg)" },
  { name: "--bks-text-editor-operator-fg-color", value: "var(--editor-operator-fg)" },
  { name: "--bks-text-editor-definition-fg-color", value: "var(--editor-definition-fg)" },
  { name: "--bks-text-editor-variableName-fg-color", value: "var(--editor-variableName-fg)" },
  { name: "--bks-text-editor-bool-fg-color", value: "var(--editor-bool-fg)" },
  { name: "--bks-text-editor-null-fg-color", value: "var(--editor-null-fg)" },
  { name: "--bks-text-editor-className-fg-color", value: "var(--editor-className-fg)" },
  { name: "--bks-text-editor-propertyName-fg-color", value: "var(--editor-propertyName-fg)" },
  { name: "--bks-text-editor-punctuation-fg-color", value: "var(--editor-punctuation-fg)" },
  { name: "--bks-text-editor-meta-fg-color", value: "var(--editor-meta-fg)" },
  { name: "--bks-text-editor-typeName-fg-color", value: "var(--editor-typeName-fg)" },
  { name: "--bks-text-editor-labelName-fg-color", value: "var(--editor-labelName-fg)" },
  { name: "--bks-text-editor-attributeName-fg-color", value: "var(--editor-attributeName-fg)" },
  { name: "--bks-text-editor-attributeValue-fg-color", value: "var(--editor-attributeValue-fg)" },
  { name: "--bks-text-editor-heading-fg-color", value: "var(--editor-heading-fg)" },
  { name: "--bks-text-editor-url-fg-color", value: "var(--editor-url-fg)" },
  { name: "--bks-text-editor-processingInstruction-fg-color", value: "var(--editor-processingInstruction-fg)" },
  { name: "--bks-text-editor-special-string-fg-color", value: "var(--editor-special-string-fg)" },
  { name: "--bks-text-editor-name-fg-color", value: "var(--editor-name-fg)" },
  { name: "--bks-text-editor-deleted-fg-color", value: "var(--editor-deleted-fg)" },
  { name: "--bks-text-editor-character-fg-color", value: "var(--editor-character-fg)" },
  { name: "--bks-text-editor-color-fg-color", value: "var(--editor-color-fg)" },
  { name: "--bks-text-editor-standard-fg-color", value: "var(--editor-standard-fg)" },
  { name: "--bks-text-editor-separator-fg-color", value: "var(--editor-separator-fg)" },
  { name: "--bks-text-editor-changed-fg-color", value: "var(--editor-changed-fg)" },
  { name: "--bks-text-editor-annotation-fg-color", value: "var(--editor-annotation-fg)" },
  { name: "--bks-text-editor-modifier-fg-color", value: "var(--editor-modifier-fg)" },
  { name: "--bks-text-editor-self-fg-color", value: "var(--editor-self-fg)" },
  { name: "--bks-text-editor-operatorKeyword-fg-color", value: "var(--editor-operatorKeyword-fg)" },
  { name: "--bks-text-editor-escape-fg-color", value: "var(--editor-escape-fg)" },
  { name: "--bks-text-editor-strong-fg-color", value: "var(--editor-strong-fg)" },
  { name: "--bks-text-editor-emphasis-fg-color", value: "var(--editor-emphasis-fg)" },
  { name: "--bks-text-editor-strikethrough-fg-color", value: "var(--editor-strikethrough-fg)" },
  { name: "--bks-text-editor-sql-alias-fg-color", value: "var(--editor-sql-alias-fg)" },
  { name: "--bks-text-editor-sql-field-fg-color", value: "var(--editor-sql-field-fg)" },
  { name: "--bks-text-editor-context-menu-bg-color", value: "var(--panel-bg)" },
  { name: "--bks-text-editor-context-menu-fg-color", value: "var(--panel-fg)" },
  { name: "--bks-text-editor-context-menu-item-bg-color-active", value: "var(--panel-bg-hover)" },
  { name: "--bks-text-editor-context-menu-item-fg-color-active", value: "var(--panel-fg)" },
  { name: "--bks-text-editor-context-menu-item-bg-color-hover", value: "var(--panel-bg-hover)" },
];
