/** CSS Variables that are passed to plugins. A plain string is read as is.
 * A `{ name, value }` entry exposes `name` with `value` resolved against the
 * app, so legacy names can alias the semantic tokens. */
export const cssVars = [
  "--font-size",
  "--font-family",
  "--font-family-mono",

  { name: "--theme-bg", value: "var(--bg-base)" },
  { name: "--theme-base", value: "var(--text-contrast)" },
  { name: "--theme-primary", value: "var(--primary-solid-bg)" },
  { name: "--theme-secondary", value: "var(--info-solid-bg)" },

  { name: "--text-dark", value: "var(--text-contrast)" },
  { name: "--text-light", value: "var(--text-a)" },
  { name: "--text-lighter", value: "var(--gray-a9)" },
  { name: "--text-hint", value: "var(--gray-a9)" },
  { name: "--text-disabled", value: "var(--gray-a9)" },

  { name: "--brand-info", value: "var(--info-solid-bg)" },
  { name: "--brand-success", value: "var(--success-solid-bg)" },
  { name: "--brand-warning", value: "var(--warning-solid-bg)" },
  { name: "--brand-danger", value: "var(--danger-solid-bg)" },
  { name: "--brand-default", value: "var(--solid-bg)" },
  { name: "--brand-purple", value: "var(--purple-9)" },
  { name: "--brand-pink", value: "var(--pink-9)" },

  "--border-color",
  "--text-muted",
  { name: "--link-color", value: "var(--link-fg)" },
  { name: "--placeholder", value: "var(--gray-a9)" },
  { name: "--selection", value: "var(--selection-bg)" },
  { name: "--input-highlight", value: "var(--primary-solid-bg)" },

  { name: "--query-editor-bg", value: "var(--bg-base)" },
  { name: "--menu-bg", value: "var(--panel-bg)" },
  { name: "--menu-shadow", value: "var(--panel-shadow)" },

  "--scrollbar-track",
  "--scrollbar-thumb",

  // Semantic color tokens (see assets/styles/themes/utilities.scss)
  "--white",
  "--black",

  "--bg-base",
  "--bg-subtle",
  "--bg",
  "--bg-hover",
  "--bg-active",
  "--border-subtle",
  "--border",
  "--border-hover",
  "--solid-bg",
  "--solid-bg-hover",
  "--text",
  "--text-contrast",
  "--bg-base-a",
  "--bg-subtle-a",
  "--bg-a",
  "--bg-hover-a",
  "--bg-active-a",
  "--border-subtle-a",
  "--border-a",
  "--border-hover-a",
  "--solid-bg-a",
  "--solid-bg-hover-a",
  "--text-a",
  "--text-contrast-a",

  "--primary-bg-base",
  "--primary-bg-subtle",
  "--primary-bg",
  "--primary-bg-hover",
  "--primary-bg-active",
  "--primary-border-subtle",
  "--primary-border",
  "--primary-border-hover",
  "--primary-solid-bg",
  "--primary-solid-bg-hover",
  "--primary-text",
  "--primary-text-contrast",
  "--primary-bg-base-a",
  "--primary-bg-subtle-a",
  "--primary-bg-a",
  "--primary-bg-hover-a",
  "--primary-bg-active-a",
  "--primary-border-subtle-a",
  "--primary-border-a",
  "--primary-border-hover-a",
  "--primary-solid-bg-a",
  "--primary-solid-bg-hover-a",
  "--primary-text-a",
  "--primary-text-contrast-a",
  "--primary-solid-fg",

  "--info-bg-base",
  "--info-bg-subtle",
  "--info-bg",
  "--info-bg-hover",
  "--info-bg-active",
  "--info-border-subtle",
  "--info-border",
  "--info-border-hover",
  "--info-solid-bg",
  "--info-solid-bg-hover",
  "--info-text",
  "--info-text-contrast",
  "--info-bg-base-a",
  "--info-bg-subtle-a",
  "--info-bg-a",
  "--info-bg-hover-a",
  "--info-bg-active-a",
  "--info-border-subtle-a",
  "--info-border-a",
  "--info-border-hover-a",
  "--info-solid-bg-a",
  "--info-solid-bg-hover-a",
  "--info-text-a",
  "--info-text-contrast-a",
  "--info-solid-fg",
  "--info-solid-fg-hover",

  "--success-bg-base",
  "--success-bg-subtle",
  "--success-bg",
  "--success-bg-hover",
  "--success-bg-active",
  "--success-border-subtle",
  "--success-border",
  "--success-border-hover",
  "--success-solid-bg",
  "--success-solid-bg-hover",
  "--success-text",
  "--success-text-contrast",
  "--success-bg-base-a",
  "--success-bg-subtle-a",
  "--success-bg-a",
  "--success-bg-hover-a",
  "--success-bg-active-a",
  "--success-border-subtle-a",
  "--success-border-a",
  "--success-border-hover-a",
  "--success-solid-bg-a",
  "--success-solid-bg-hover-a",
  "--success-text-a",
  "--success-text-contrast-a",
  "--success-solid-fg",
  "--success-solid-fg-hover",

  "--warning-bg-base",
  "--warning-bg-subtle",
  "--warning-bg",
  "--warning-bg-hover",
  "--warning-bg-active",
  "--warning-border-subtle",
  "--warning-border",
  "--warning-border-hover",
  "--warning-solid-bg",
  "--warning-solid-bg-hover",
  "--warning-text",
  "--warning-text-contrast",
  "--warning-bg-base-a",
  "--warning-bg-subtle-a",
  "--warning-bg-a",
  "--warning-bg-hover-a",
  "--warning-bg-active-a",
  "--warning-border-subtle-a",
  "--warning-border-a",
  "--warning-border-hover-a",
  "--warning-solid-bg-a",
  "--warning-solid-bg-hover-a",
  "--warning-text-a",
  "--warning-text-contrast-a",
  "--warning-solid-fg",
  "--warning-solid-fg-hover",

  "--danger-bg-base",
  "--danger-bg-subtle",
  "--danger-bg",
  "--danger-bg-hover",
  "--danger-bg-active",
  "--danger-border-subtle",
  "--danger-border",
  "--danger-border-hover",
  "--danger-solid-bg",
  "--danger-solid-bg-hover",
  "--danger-text",
  "--danger-text-contrast",
  "--danger-bg-base-a",
  "--danger-bg-subtle-a",
  "--danger-bg-a",
  "--danger-bg-hover-a",
  "--danger-bg-active-a",
  "--danger-border-subtle-a",
  "--danger-border-a",
  "--danger-border-hover-a",
  "--danger-solid-bg-a",
  "--danger-solid-bg-hover-a",
  "--danger-text-a",
  "--danger-text-contrast-a",
  "--danger-solid-fg",
  "--danger-solid-fg-hover",

  "--app-bg",
  "--app-fg",
  "--btn-icon-fg",
  "--btn-icon-fg-hover",
  "--btn-fg",
  "--btn-bg",
  "--btn-bg-hover",
  "--btn-fg-hover",
  "--btn-bg-active",
  "--btn-shadow",
  "--btn-flat-fg",
  "--btn-flat-fg-hover",
  "--btn-flat-bg",
  "--btn-flat-bg-hover",
  "--btn-flat-shadow",
  "--btn-primary-fg",
  "--btn-primary-fg-hover",
  "--btn-primary-bg",
  "--btn-primary-bg-hover",
  "--btn-primary-shadow",
  "--input-bg",
  "--input-fg",
  "--input-border",
  "--input-border-focus",
  "--link-fg",
  "--selection-bg",
  "--selection-fg",
  "--titlebar-bg",
  "--titlebar-fg",
  "--titlebar-inactive-bg",
  "--titlebar-inactive-fg",
  "--sidebar-bg",
  "--sidebar-fg",
  "--panel-bg",
  "--panel-fg",
  "--panel-shadow",
  "--overlay-bg",
  "--badge-bg",
  "--badge-fg",

  // BksTextEditor
  "--bks-text-editor-activeline-bg-color",
  "--bks-text-editor-activeline-gutter-bg-color",
  "--bks-text-editor-atom-fg-color",
  "--bks-text-editor-bg-color",
  "--bks-text-editor-bracket-fg-color",
  "--bks-text-editor-builtin-fg-color",
  "--bks-text-editor-comment-attribute-fg-color",
  "--bks-text-editor-comment-def-fg-color",
  "--bks-text-editor-comment-fg-color",
  "--bks-text-editor-comment-tag-fg-color",
  "--bks-text-editor-comment-type-fg-color",
  "--bks-text-editor-cursor-bg-color",
  "--bks-text-editor-fatcursor-bg-color",
  "--bks-text-editor-def-fg-color",
  "--bks-text-editor-error-bg-color",
  "--bks-text-editor-error-fg-color",
  "--bks-text-editor-fg-color",
  "--bks-text-editor-focused-outline-color",
  "--bks-text-editor-font-size",
  "--bks-text-editor-foldgutter-fg-color",
  "--bks-text-editor-foldgutter-fg-color-hover",
  "--bks-text-editor-gutter-bg-color",
  "--bks-text-editor-gutter-border-color",
  "--bks-text-editor-guttermarker-fg-color",
  "--bks-text-editor-guttermarker-subtle-fg-color",
  "--bks-text-editor-header-fg-color",
  "--bks-text-editor-highlight-bg-color",
  "--bks-text-editor-indent-marker-bg-color",
  "--bks-text-editor-indent-marker-active-bg-color",
  "--bks-text-editor-keyword-fg-color",
  "--bks-text-editor-linenumber-fg-color",
  "--bks-text-editor-linenumber-active-fg-color",
  "--bks-text-editor-link-fg-color",
  "--bks-text-editor-matchingbracket-fg-color",
  "--bks-text-editor-matchingbracket-bg-color",
  "--bks-text-editor-number-fg-color",
  "--bks-text-editor-property-fg-color",
  "--bks-text-editor-selected-bg-color",
  "--bks-text-editor-matchingselection-bg-color",
  "--bks-text-editor-string-fg-color",
  "--bks-text-editor-tag-fg-color",
  "--bks-text-editor-variable-2-fg-color",
  "--bks-text-editor-variable-3-fg-color",
  "--bks-text-editor-variable-fg-color",
  "--bks-text-editor-namespace-fg-color",
  "--bks-text-editor-type-fg-color",
  "--bks-text-editor-class-fg-color",
  "--bks-text-editor-enum-fg-color",
  "--bks-text-editor-interface-fg-color",
  "--bks-text-editor-struct-fg-color",
  "--bks-text-editor-typeParameter-fg-color",
  "--bks-text-editor-parameter-fg-color",
  "--bks-text-editor-enumMember-fg-color",
  "--bks-text-editor-decorator-fg-color",
  "--bks-text-editor-event-fg-color",
  "--bks-text-editor-function-fg-color",
  "--bks-text-editor-method-fg-color",
  "--bks-text-editor-macro-fg-color",
  "--bks-text-editor-label-fg-color",
  "--bks-text-editor-regexp-fg-color",
  "--bks-text-editor-operator-fg-color",
  "--bks-text-editor-definition-fg-color",
  "--bks-text-editor-variableName-fg-color",
  "--bks-text-editor-bool-fg-color",
  "--bks-text-editor-null-fg-color",
  "--bks-text-editor-className-fg-color",
  "--bks-text-editor-propertyName-fg-color",
  "--bks-text-editor-punctuation-fg-color",
  "--bks-text-editor-meta-fg-color",
  "--bks-text-editor-typeName-fg-color",
  "--bks-text-editor-labelName-fg-color",
  "--bks-text-editor-attributeName-fg-color",
  "--bks-text-editor-attributeValue-fg-color",
  "--bks-text-editor-heading-fg-color",
  "--bks-text-editor-url-fg-color",
  "--bks-text-editor-processingInstruction-fg-color",
  "--bks-text-editor-special-string-fg-color",
  "--bks-text-editor-name-fg-color",
  "--bks-text-editor-deleted-fg-color",
  "--bks-text-editor-character-fg-color",
  "--bks-text-editor-color-fg-color",
  "--bks-text-editor-standard-fg-color",
  "--bks-text-editor-separator-fg-color",
  "--bks-text-editor-changed-fg-color",
  "--bks-text-editor-annotation-fg-color",
  "--bks-text-editor-modifier-fg-color",
  "--bks-text-editor-self-fg-color",
  "--bks-text-editor-operatorKeyword-fg-color",
  "--bks-text-editor-escape-fg-color",
  "--bks-text-editor-strong-fg-color",
  "--bks-text-editor-emphasis-fg-color",
  "--bks-text-editor-strikethrough-fg-color",
  "--bks-text-editor-sql-alias-fg-color",
  "--bks-text-editor-sql-field-fg-color",

  // BksTextEditor context menu
  "--bks-text-editor-context-menu-bg-color",
  "--bks-text-editor-context-menu-fg-color",
  "--bks-text-editor-context-menu-item-bg-color-active",
  "--bks-text-editor-context-menu-item-fg-color-active",
  "--bks-text-editor-context-menu-item-bg-color-hover",
] as const;
