name: Studio - Docs Publish

on: 
  push:
    tags:
      - "v*"


jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: yarn install --frozen-lockfile
      
      - name: Build
        run: yarn workspace beekeeper-studio run docs:build
      
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=apps/studio/docs/.vuepress/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
